spring:

  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.103:3306/wangyistudy?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: loginservice



mybatis:
  mapperLocations: classpath*:mybatis/*Mapper.xml

  redis:
    host: 127.0.0.1
    port: 6379
    pass:
    maxIdle: 300
    maxActive: 600
    maxWait: 1000
    testOnBorrow: true


eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.103:1111/eureka/

server:
  port: 8086
